"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
#import os
#
#yadahoo = []
#a = os.listdir('modules')
#b = os.listdir('images')
#c = os.listdir('sounds')
#total = [a,b,c]
#print(total)
#r = ''
#h = ''
#for r in total:
#    for h in r:
#        yadahoo.append(h)
#
#yadahoo.append('FacillimumLibraryMATH.py')
#yadahoo.append('math game logo.png')
#print(yadahoo)


APP = ['main.py']
DATA_FILES = ['FacillimumLibraryMATH.py','math game logo.png','images','modules','sounds']
OPTIONS = {}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
